config/routes.rb
Rails.application.routes.draw do
  resources :opportunities
  root 'application#welcome'


  resources :users, only: [:new, :create]
  get '/sign_up' => 'application#sign_up'
  get '/log_in' => 'application#log_in'
  get '/find' => 'application#search'
  post '/find' => 'opportunities#find'
  get '/results/' => 'opportunities#results'
  post '/results/' => 'opportunities#find'
  #session
  # get '/session' => 'session#current_user'
  post '/session' => 'session#create'
  delete '/session' => 'session#destroy'
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true, uniqueness: true
  validates :password_digest, presence: true

  validates :password,  length: {
    minimum: 8
  }
  has_many :opportunities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def welcome
    render '/welcome'
  end

  def sign_up
    render '/sign_up'
  end

  def log_in
    render '/log_in'
  end

  def search
    render '/find'
  end

  private

  def current_user
    @current_user ||= session[:current_user_id] &&
    User.find(session[:current_user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_current_user
    redirect_to root_path unless logged_in?
  end

end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController

  $KARMA_ACCOUNT_NAME  = ENV["KARMA_ACCOUNT_NAME"]
  $KARMA_ACCOUNT_KEY = ENV["KARMA_ACCOUNT_KEY"]

  def find
    @location = opportunity_params[:city]
    api = VolunteerMatchApi.new($KARMA_ACCOUNT_NAME, $KARMA_ACCOUNT_KEY)
    $opps = api.search(@location) # JSON {"name":"VolunteerMatch","result":"Hello VolunteerMatch!"}

    redirect_to results_path
  end

  def results
    $opps
    render '/opportunities/index'
  end

  private

  def opportunity_params
    return params.require(:location).permit(:city)
  end

end

class VolunteerMatchApi

  def initialize (account_name, api_key)
    @account_name = account_name
    @api_key      = api_key
  end

  def search (city)
    call :searchOpportunities,
    { :opportunityTypes => ["public"],
      :location => city,
      :sortCritera => "distance",
      :sortOrder => "desc"
    }.to_json
  end

  def call(action, json_query)
    puts action
    puts json_query
    nonce           = Digest::SHA2.hexdigest(rand.to_s)[0, 20]
    creation_time   = Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S%z")
    password_digest = Base64.encode64(Digest::SHA2.digest(nonce + creation_time + @api_key)).chomp
    url             = URI.parse("http://www.volunteermatch.org/api/call?action=#{action.to_s}&query=#{json_query}")
    req             = Net::HTTP::Get.new(url.request_uri)
    req.add_field('Content-Type', 'application/json')
    req.add_field('Authorization', 'WSSE profile="UsernameToken"')
    req.add_field('X-WSSE', 'UsernameToken Username="' + @account_name + '", PasswordDigest="' + password_digest + '", ' +
        'Nonce="' + nonce + '", Created="' + creation_time + '"')

    res = Net::HTTP.new(url.host, url.port).start { |http| http.request(req) }
    raise "HTTP error code #{res.code}" unless res.code == "200"
    @results = OpenStruct.new(JSON.parse res.body)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    user = User.find_by(name: user_params[:name])

    if user && user.authenticate(user_params[:password])
      session[:current_user_id] = user.id
      redirect_to find_path
    else
      flash[:message]  = "Email / Password combo does not exist"
      redirect_to root_path
    end
  end

  def destroy
    session[:current_user_id] = nil

    redirect_to root_path
  end

  private
  def user_params
    return params.require(:user).permit(:name, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def create
  @user = User.new(user_params)

  if @user.save
      redirect_to find_path
  else
    redirect_to root_path
  end



end

private
def user_params
  return params.require(:user).permit(:name, :password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>karma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <%= javascript_include_tag 'app', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
</head>
<header>
  <h2>Where would you like to make a difference today?</h2>
  <div class="logo">
    KARMA
  </div>
  <% if current_user %>
    <form class="logout" action= "<%= session_path %>" method="POST">
      <input type="hidden" name="_method" value="DESTROY">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="Logout">
    </form>
  <% end %>
</header>
<body>

<%= yield %>

</body>
</html>

app/views/opportunities/index.html.erb
<form class="find" action= "<%= results_path %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>choose a city</label>
  <input class="city" type="text" name="location[city]" >
  <input type="submit" value="find">
</form>
<div class="results">
  <ul>
  <% $opps[:opportunities].each do |opp| %>
    <li>
      <h4><%=opp["parentOrg"]["name"]%> | <%=opp["location"]["city"]%> | <%= opp["title"] %></h4>
      <p>
      <%= opp["plaintextDescription"] %>
      <%= opp["vmRrl"]%>
      <p>
      <!-- <form action="<%= results_path %>" method="POST">
        <input type="submit" name="name" value="Save Opportunity">
      </form> -->
    </li>
  <% end %>
  </ul>
</div>

app/views/users/welcome.html.erb
<form class="<%= users_path %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="user[name]" placeholder="First name"></br>
  <input type="password" name="user[password]" placeholder="Password"></br>
  <input type="submit"  value="submit">
</form>